# Generated by Django 3.2.5 on 2021-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_rename_recursos_recurso'),
        ('core', '0002_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='recurso',
            field=models.ManyToManyField(to='atracoes.Recurso'),
        ),
    ]
