# Generated by Django 3.2.5 on 2021-07-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracao',
            new_name='Recursos',
        ),
    ]
